trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'

- bash: bundle install --path vendor/bundle
  displayName: 'Install Jekyll'

- bash: ./build.sh
  displayName: 'Build the pages'
