trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: '$(UPLOAD_HOST) ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOqZ29t8GJA17GIM8g7MQEDMibZaFleaXRz32fWQ3iJU/XKEa/bSfjQSbdlMmo7qcwIFc2frYOM4sllcq8MNxys='
    sshPublicKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGtHejxpO/1lrN/aRRp5wFnJTuowWY/eTf4hiFJk84HQ aosc@aosc'
    sshPassphrase: '$(KEY_PASSWD)'
    sshKeySecureFile: 'upload_key'
  condition: ne(variables['Build.Reason'], 'PullRequest')

- task: UseRubyVersion@0
  displayName: 'Select Ruby version'
  inputs:
    versionSpec: '>= 2.4'
    addToPath: true

- bash: gem install bundler && bundle install --path vendor/bundle
  displayName: 'Install Jekyll'

- bash: ./build.sh
  displayName: 'Build the pages'

- bash: rsync -rlOvhze ssh --progress _site/* 'upload@$(UPLOAD_HOST):/var/www/aosc-portal/'
  displayName: 'Upload the files'
  condition: ne(variables['Build.Reason'], 'PullRequest')
