DefaultContentLanguage = "en"
baseURL = "https://aosc.io/"
hasCJKLanguage = true
disablePathToLower = true

[languages]
  [languages.en]
    languageName = "English"
    title = "AOSC Portal"
    weight = 1
  [languages.zh-cn]
    languageName = "简体中文"
    title = "AOSC 社区门户"
    weight = 2
  [languages.zh-tw]
    languageName = "繁體中文（台灣）"
    title = "AOSC 社群入口"
    weight = 3
  [languages.lzh]
    languageName = "繁體中文（台灣・豎排）"
    title = "AOSC 社群入口"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
        typographer = false # disable smart quotes
